### ISSUE TITLE
How to run server.php on cpanel?

### ISSUE THREAD

**Issue by haider-pw** [kishor10d/CodeIgniter-Ratchet-Websocket#1]
First of all Many thanks for making this demo script for helping others like me to understand how we can use sockets.
I want to know how to run server.php on CPANEL??
I am using shared Hosting. Will it work on shared hosting also.??

**Comment by kishor10d** [comment]
Yes, it will work on Shared Hosting too. Once write a CRON job to hit the server.php.
Delete the cron job after that.

**Comment by haider-pw** [comment]
Thankyou for your response. 

But please tell how to make it work through cron job. 

I searched, i know that cron job does work on schedule. 

but how to run this command `c:/>php server.php` from a php file??

**Comment by kishor10d** [comment]
@pakistanihaider 
Cron Job : 
You can create a per minute(\* \* \* \* *) cron job in cpanel by following command:
<code>php public_html/ratchet/application/third_party/Realtime/bin/server.php</code>

You asked about shared hosting, I tried for shared hosting but its not working because of proper user permissions. My shared hosting user don't as much permissions.

Check this issue and comment by Ratchet developer:

https://github.com/ratchetphp/Ratchet/issues/409

Now I am running this socket on my VPS, so I don't have any problem.

**Comment by zawaruddin** [comment]
i've running on local and don't have problem.
But when i upload to server and access my domain, i have js error message

```
Firefox can't establish a connection to the server at ws://localhost:2000/.
this.socket = new WebSocket("ws://" + url);
```

nb : 
i've run cli `php ratchet/application/third_party/Realtime/bin/server.php` on my server

**Comment by zawaruddin** [comment]
well now it's work on my server....

just change constant BROADCAST_URL from 'localhost' into my domain name.
- i've try to change 'localhost' into IP Public, but didnt work...

**Comment by Mecanik** [comment]
This is very bad idea, and those who tell you these "hackish" ways as well.

You must absolutely NOT run websocket server in shared hosting environment. 

Use a VPS for the websocket server, there are servers out there for 2$/month.

**Comment by iampeters** [comment]
@Mecanik what do you mean by BROADCAST_URL? please kindly put me through i just hosted a websocket app with ratchet php websocket and i have set the cron job to run every minute but i still get 
<code>Firefox can't establish a connection to the server at ws://localhost:2000/.</code> erorr;
thanks in advance

**Comment by Mecanik** [comment]
I did not say anything about any URL, what I did say is you cannot and you should not run a web socket server in a shared hosting environment.

**Comment by iampeters** [comment]
@Mecanik that question was actually meant for @zawaruddin. Sorry about that.

**Comment by iampeters** [comment]
@zawaruddin please kindly tell me how you got yours to work cause i'm still unable to get my websocket server running on cpanel.
i changed the broadcast url from <code>var conn = new WebSocket('ws://localhost:8080');</code>  to <code>var conn = new WebSocket('ws://my-domain:8080');</code> but it still has not worked.
On my cpanel, i entered the cron job this way: <code>* * * * * /usr/local/bin/php -q /home/my-username/public_html/file/to/run </code>.

Thanks

**Comment by iampeters** [comment]
I have finally gotten it to work. i did not include the file path correctly.

**Comment by bienbasal** [comment]
Hello @iampeters , I saw this thread I'm having an issue with the ratchet. I uploaded the files and used cron jobs to execute the serve.php and it works. My problem is checking the connection, I got this issue:

> var conn = new WebSocket('ws://mywebsite.com:8080');
> conn.onopen = function(e) {
>     console.log("Connection established!");
> };
> conn.onmessage = function(e) {
>     console.log(e.data);
> };
> 
> VM141:1 WebSocket connection to 'ws://mywebsite.com:8080' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by iampeters** [comment]
Did you check if the cron job started successfully?
Also check for error logs on the server in the same directory where the
server.php is hosted.

**Comment by bienbasal** [comment]
@iampeters  yes the cron jobs works successfully i also received an email that server is started. 
What I did 

1. I opened the browser, 
2 Visit my website
3. I press F12 and pasted this code 

> var conn = new WebSocket('ws://localhost:8080');
> conn.onopen = function(e) {
>     console.log("Connection established!");
> };
> 
> conn.onmessage = function(e) {
>     console.log(e.data);
> };
> 

from the http://socketo.me/docs/hello-world website. Then I changed the localhost to my website url.

Did i make the right way of checking the connection? Im newbie in websockets.

**Comment by iampeters** [comment]
@bienbasal 
This is what i think you should do:
1) create another file for testing purposes (test.html) on your server;
2) at the bottom of the file, right after or before the closing <code>&lt;/body&gt;</code> tag. Paste this code:
<blockquote>
<script>

    var conn = new WebSocket('ws://your-domain:8080');
    conn.onopen = function(e) {
    console.log("Connection established!");
    };
    conn.onmessage = function(e) {
    console.log(e);
    };
</script>
</blockquote>

3) now run the page and check the console if it logged <code>Connection established!</code>.

Try this and lets see the output.

**Comment by bienbasal** [comment]
@iampeters , yes I did, i created a one php page, and I pasted this code. But still i got the error in both http and https, I also asked the tech support and they told me that port 80 is open. :(

**WebSocket connection to 'wss://website.com:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

> <script>
> var conn = new WebSocket('ws://your-domain:8080');
> conn.onopen = function(e) {
> console.log("Connection established!");
> };
> conn.onmessage = function(e) {
> console.log(e);
> };
> </script>

**Comment by iampeters** [comment]
the error message received shows you are using a secured websocket connection <b>WebSocket connection to <kbd>'wss://website.com:8080/' </kbd>failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED</b>

Check these few things:
1) Confirm from your tech support whether websocket is secured. if is, try using this <code>var conn = new WebSocket(wss://your-domain:8080);</code>
2) Also check if you have ssl certificate installed on your actual domain. the connection will be refused if you use an insecure WebSocket.

**Comment by komputronika** [comment]
Good article that explain complete steps to run socket server on linux based VPS.

https://www.digitalocean.com/community/tutorials/how-to-develop-a-node-js-tcp-server-application-using-pm2-and-nginx-on-ubuntu-16-04

**Comment by gajananchitare** [comment]
I have google cloud hosting
i have run my php-socket.php using whm terminal, it runs and also shown in telnet

but websocket connection is open and close immediate 

my firefox shows error as [Firefox can’t establish a connection to the server at wss://domain:port/beta/chat_socket/php-socket.php.]

**Comment by Brian1111** [comment]
How can I create a CRON job on GoDaddy shared hosting site?   Should it be as follows?
`php public_html/ratchet_hello_world/bin/server.php`  or should I write it differently?
Also what should I put for port number on bin/server.php file instead of 8080?

**Comment by diaz3801** [comment]
Open cpanel terminal. Run php your-websocket.php. Use ws://your-domain:8080
