### ISSUE TITLE
Messages retrieving Issue

### ISSUE THREAD

**Issue by shayanali995** [kishor10d/CodeIgniter-Ratchet-Websocket#11]
Hello,

When i sent a message connectionMessage client side not working after refreshing sender page then its receiving real time on other computer.

Thanks,

**Comment by kishor10d** [comment]
@shayanali995 : sorry for delay. Not getting what you are trying to say.

**Comment by shayanali995** [comment]
Please tell me how to connect on SSL website ? do i needs to use just IP with WSS or domain name ?

**Comment by shayanali995** [comment]
I have root access of server but socket is going offline i don't know why can you explain what should i do to run continuously without any delays, Thanks

**Comment by kishor10d** [comment]
1) You can use domain name instead IP address. It works with subdomains too.
2) Socket will not run continuously after 10 minutes of inactive session. You need to use ping-pong mechanism to make it running continuously. It means, you have to send a blank message before 10 minutes.

**Comment by shayanali995** [comment]
Can i use cron job for server.php instead of 2nd method ? also clear me do i hit server.php or anything else ?

**Comment by kishor10d** [comment]
No, if a websocket already working on that ip address and port then it will throw error on server side.

**Comment by shayanali995** [comment]
Then how to use this suggested method can you explain me little ?

**Comment by kishor10d** [comment]
You need to create a method which send an automatic blank message say "hello world" within 10 minutes.
It will extends the life of websocket server for next 10 minutes. Don't do UI changes or DB calls withing this method.

In current repository, there is a method named ``` addSystemMessage ``` in file [https://github.com/kishor10d/CodeIgniter-Ratchet-Websocket/blob/master/assets/app/Connection.js](Connection.js), which is a written for blank message. Just call that method in your ```setInterval``` function.

**Comment by kishor10d** [comment]
@shayanali995 : Hey, You need to start websocket once using cron job. Later on just stop that cron job. Once the websocket starts, you don't need to start it again. Just stay it awake. If it go to sleep then you need hit cron job again. Till date, I am unable to find the full proof method to make websocket awake all the time. Once I get that, I will update the repository.

**Comment by shayanali995** [comment]
Hi please tell me i am trying to connect websocket but having this error 
failed: WebSocket opening handshake timed out

**Comment by shayanali995** [comment]
Hi,

My websocket listening at 0.0.0.0:8080 i have check this from root access not able to connect on SSL i have created proxy everything has done from my side also using cloudfare SSL and other services 

Please help me 

Thanks,
