### ISSUE TITLE
Can you create example using pure JS or using jQuery?

### ISSUE THREAD

**Issue by zawaruddin** [kishor10d/CodeIgniter-Ratchet-Websocket#2]

**Comment by kishor10d** [comment]
@zawaruddin : Yes, Actually I already done with it, I just have to modify it for general use and soon I will update the same with jQuery...

**Comment by zawaruddin** [comment]
thank you... :+1:

**Comment by kishor10d** [comment]
@zawaruddin : I implemented the functionality using jQuery and committed it.
For your better understanding, I simply added 3 new files in same project.

Controller : Jquery.php
View : jquery.php
Assets/App : Connection2.js

Please go through these files.

Thanks for using library

**Comment by zawaruddin** [comment]
OK... thanks again... 
i'll check it... :)
