### ISSUE TITLE
How to get Chat app into CI_Controller

### ISSUE THREAD

**Issue by dreammonkey** [kishor10d/CodeIgniter-Ratchet-Websocket#4]
hi there, very interesting project !

I was thinking if it could be possible to somehow make your Chat.php class extend from CI_Controller ?
This would make a huge difference in terms of writing the chat server logic, one could insert data in the database directly from the socket server (using CI models and querybuilder classes... , among other things).

I tried extending from My_Controller but off course the application needs to fully integrate with the framework, I'm a bit puzzled if and how this could be accomplished... There might be security issues and of course the use of the session class could cause some unexpected behaviour, but still I think this could be worth taking a look at...

Excuse me if my question is not clear, basically I would be able to do this :

`````` php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;

class Chat extends MY_Controller implements MessageComponentInterface {

    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        // not used...
    }

    public function onOpen(ConnectionInterface $conn) {
    }

    public function onMessage(ConnectionInterface $from, $msg) {
    }

    public function onClose(ConnectionInterface $conn) {
    }

    public function onError(ConnectionInterface $conn, \Exception $e) {
    }

}

/* End of file Chat.php */
/* Location: ./application/controllers/Chat.php */```
``````

**Comment by kishor10d** [comment]
@dreammonkey :+1:  Your thinking is correct, I am also trying for the same thing. I was little busy from in back days, now I am thinking to work on this. If you have something to update the fork the repo and make changes.
Thanks.

**Comment by dreammonkey** [comment]
hi @kishor10d !
I haven't had the time to really dig into this, I had a few goes, but I couldn't get it running.
I think the trick is to somehow get the server started through CLI, but the CI CLI doesn't really expect to be kept running...

**Comment by kishor10d** [comment]
@dreammonkey : Once I run the CLI through cron job and kept it running. At that time it was working. Please try it. We will find some solution over the Ping-Pong mechanism to keep websocket running.

**Comment by Ateeqkhalil** [comment]
did anyone found the solution for @dreammonkey question yet ?
