### ISSUE TITLE
Server.php problem in cpanel

### ISSUE THREAD

**Issue by sabyer** [kishor10d/CodeIgniter-Ratchet-Websocket#5]
I was able to run server.php in cpanel using cron, but i am getting this error

<b>Fatal error</b>:  Uncaught exception 'React\Socket\ConnectionException' with message 'Could not bind to tcp://0.0.0.0:2000: Address already in use'

**Comment by kishor10d** [comment]
Have you changed the BROADCAST_URL constant for your domain?

You asked about shared hosting, I tried for shared hosting but its not working because of proper user permissions. My shared hosting user don't as much permissions.

Check this issue and comment by Ratchet developer:

ratchetphp/Ratchet#409

**Comment by sabyer** [comment]
Thank you for replying. Its okay now, I used command netstat -tulpen and I see 0.0.0.0:2000. I already have changed the constants. I followed your instructions  but I am getting this error in console

angular.min.js:108Error: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Error (native)
    at Object.sendMsg (http://mydomain.com/chat/assets/app/Connection.js:36:22)
    at http://mydomain.com/chat/assets/app/secondCtrl.js:18:21
    at http://mydomain.com/chat/assets/js/angular.min.js:86:360
    at http://mydomain.com/chat/assets/js/angular.min.js:120:113
    at m.$eval (http://mydomain.com/chat/assets/js/angular.min.js:134:398)
    at m.$digest (http://mydomain.com/chat/assets/js/angular.min.js:131:427)
    at m.$apply (http://mydomain.com/chat/assets/js/angular.min.js:135:161)
    at l (http://mydomain.com/chat/assets/js/angular.min.js:87:152)
    at N (http://mydomain.com/chat/assets/js/angular.min.js:91:187)(anonymous function) @ angular.min.js:108(anonymous function) @ angular.min.js:80(anonymous function) @ angular.min.js:120$eval @ angular.min.js:134$digest @ angular.min.js:131$apply @ angular.min.js:135l @ angular.min.js:87N @ angular.min.js:91x.onload @ angular.min.js:92
VM49:35 WebSocket connection to 'ws://mydomain.com:2000/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by sabyer** [comment]
And I was not the one who asked about shared hosting

**Comment by kishor10d** [comment]
@sabyer : ok... Are you executing same project or you done with any changes in it..? Because, after your question, I re-deployed it and it run smoothly.

**Comment by sabyer** [comment]
I just realized now that I am using shared hosting hehe, not really familiar with these things. I am now getting this error, connection refused. Is this about firewall or is it really not going to work in shared hosting?  VM311:35 WebSocket connection to 'ws://mydomain.com:2000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by kishor10d** [comment]
@sabyer : sorry for delay in reply. Actually the websocket will not work in Shared Hosting. You need atleast VPS or Dedicated Server and SSH access for this.
