### ISSUE TITLE
Error of BROADCAST_URL

### ISSUE THREAD

**Issue by d33pak-s1ngh** [kishor10d/CodeIgniter-Ratchet-Websocket#7]
when i try to run command php server.php got following error the value of 
BROADCAST_URL is set to a localhost ip that is 127.0.0.1 .
![socket](https://cloud.githubusercontent.com/assets/23626544/23610961/e25fbae6-029a-11e7-800b-f0ef6a96b66d.png)

**Comment by d33pak-s1ngh** [comment]
i want to create a socket through which i can listen notification on android device whenever admin issues any notification.
i am using codeigniter for server side coding with mysql.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : Actually you need to provide your real-ip-address, which is generated by your lan network. e.g. 192.168.0.234

Please check with command "_ifconfig_" and replace ip-address with that one. It will work.

**Comment by d33pak-s1ngh** [comment]
i try that i used ipchickn to check my ip and then try that i.p still got
same error

**Comment by kishor10d** [comment]
@d33pak-s1ngh : please upload the screenshot. We will look into it together.

**Comment by d33pak-s1ngh** [comment]
ok i tried in windows 7 without changing value of BROADCAST_URL it is on its default 192.168.0.6 and i enter a value in textbox and value is getting stored in to database without any page refresh so this what websocket do??

this can be done with ajax also

what i want to do is that whenever any record insert into database i should get notifcation in android app that record has been inserted. can we do that with this websocket plugin which you have provided.

**Comment by d33pak-s1ngh** [comment]
the real purpose of using websocket is that we can consume server side events and actions at client side without any page refresh. client can be android or ios app or even a web app itself.
so if an admin will generate any notification from web app an android device listening to websocket should receive a notifcation without any action performed.

thank you for any kind of help.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : I think you didn't read README.md. It is doing the same thing what are you thinking about. It is doing without page-refresh. It is just the matter of setting it up properly. I think you didn't started websocket server.

**Comment by d33pak-s1ngh** [comment]
how do i start a websocket server?
i tried to run command 
php server.php which throws following error

**Comment by d33pak-s1ngh** [comment]
following is the setting in constant.php it contains my ip address and i change port from 2000 to 8181 just for testing but still getting error.
/** WEBSOCKETS BROADCAST TYPES **/

define("POST",					"post");
define("BROADCAST_URL",			"116.72.11.241");
define("BROADCAST_PORT",		"8181");


Following is screenshot of error saying that address is already in use.

![sock1](https://cloud.githubusercontent.com/assets/23626544/23642335/da3a9f86-031f-11e7-95c1-fa9ea6f5018d.png)

**Comment by kishor10d** [comment]
@d33pak-s1ngh : Remember, this code will **not** work on **shared hosting server** (known issue). Also if you wanna test it on localhost then you must give the _ip-address_ of your machine over _LAN_ (i.e. 192.168.1.xxx like that).

**Comment by d33pak-s1ngh** [comment]
ok so i will host it on server and use that ip to test.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : I think we have a skype call where I will show you how it work,

My skype username : kishor.itg

**Comment by d33pak-s1ngh** [comment]
will do it sure i want to understand  socket

**Comment by d33pak-s1ngh** [comment]
hii @kishor10d  i think everything working fine except that connection.js is not able to make connection with socket server check the following from firefox browser.
![socket](https://cloud.githubusercontent.com/assets/23626544/23782631/d08a2db8-057b-11e7-95c1-02fd497b00ce.png)

all this is happening because php server.php command is not executing the script successfully it throws error of BROADCAST_URL error.

you are saying that i have to provide lan ip as value of BROADCAST_URL that is also fine.

but i have 2 machines  connect with same lan ip and you are saying that it will not work with share hosting server so what should i do?
how i can set an ip?
please help me to understand.
thank you.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : You need to keep the websocket server _running_. That warning means your socket is not running. Also instead of ip_address you can give your domain name also. (e.g. example.com). If you have _**root**_ access then you can make it run on your shared hosting too.

Websocket server cannot be keep running, so you have to ping it after some interval. You can schedule a cron job (dirty practice) or refer this http://stackoverflow.com/questions/19487664/how-do-i-keep-a-websocket-server-running-even-after-i-close-the-ssh-terminal

**Comment by d33pak-s1ngh** [comment]
i dont have a domain name i have an ip address of my server and i have a root access of that server
i have hosted your application on that and i am accessing it from server like 
104.131.2.03/socket

**Comment by d33pak-s1ngh** [comment]
whenever i type command php server.php it doesnt give any result then i have to interrupt the service and again fire the command than it gives error that address is already in use.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : It doesn't give any result means it is working. Don't interupt it. and try from your browser.

**Comment by d33pak-s1ngh** [comment]
finally found the problem and now it is working fine. i open in two tabs and enter some value from one tab which is now appear's in both tab.

the problem was after typing command php server.php there was no result so i press ctl+z to stop it then again i try php server.php then it throws error that address is in use because in previous command it started websocket server but after typing it again mess the port.

**Comment by d33pak-s1ngh** [comment]
thanx kishor i got it but now the problem is i cant keep my cmd open all time . this thing should be running in background all the time. what should i do for it??

**Comment by d33pak-s1ngh** [comment]
also i checked your admin panel in codeigniter in **codeinsect** how i can add this socket feature in to that codeigniter panel?

**Comment by kishor10d** [comment]
Here is the solution for your command line problem. Also you can free your ports by killing the process. Everything explain in the following url.
Please refere this url :
http://stackoverflow.com/questions/19487664/how-do-i-keep-a-websocket-server-running-even-after-i-close-the-ssh-terminal


And you ask about CodeInsect Admin Panel, actually it is ready admin panel and you can add your features into it. Its your choice that how you integrate your code into it. Just copy and paste the same things of third_party folder, and implement the controllers into controllers. You can do it easily.

**Comment by d33pak-s1ngh** [comment]
ook thank you for this awesome work i will try to merge admin panel with socket and inform u.
