### ISSUE TITLE
how to push data from server side?

### ISSUE THREAD

**Issue by masoud005** [kishor10d/CodeIgniter-Ratchet-Websocket#8]
hi 
is it possible to send data from server side?
if possible, then how?

**Comment by charlie-eth** [comment]
Wondering about how to do this as well, did anyone manage to do it?

**Comment by kishor10d** [comment]
You know, we can run script on server by using schedule jobs or cron jobs. Using cron you can push data from server side. Till yet, I didn't manage to do that.
